
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: api
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://root:example@mongo:27017/demo
      - KEY_PEM=/app/certs/key.pem
      - CERT_PEM=/app/certs/cert.pem
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: >
      sh -c "npm run dev"
    networks:
      - app-network
    restart: always
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:
  mongo-config:

networks:
  app-network:
